FROM nginx:1.27-alpine

# Remove default config
RUN rm /etc/nginx/conf.d/default.conf

# Copy custom config
COPY nginx.conf /etc/nginx/conf.d/devxgen.conf

EXPOSE 80 443

CMD ["nginx", "-g", "daemon off;"]
